dist: xenial
language: python
python:
  - "3.6"
  - "3.5"
  - "3.7"
  
branches:
  only:
  - master
  - dev
  - test

install:
  - pip install -r requirements.txt

script:
  - python src/run_tests.py -v

